<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Claqueta - Reseñas de Pelis</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href=<?php echo BASE_URL ?> >🎬 La Claqueta </a>
                
                <button class="navbar-toggler" type="button" id="btn-menu">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo BASE_URL; ?>peliculas">Ver Todas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo BASE_URL; ?>categorias">Categorías</a>
                        </li>
                        
                            <?php if(isset($_SESSION['USER_ID'])): ?>
                            <li class="nav-item">
                                <a class="nav-link text-warning" href="<?php echo BASE_URL ?>agregar">Agregar Película</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-warning" href="<?php echo BASE_URL ?>administrar">Gestionar Categorías</a>
                            </li>
                        <?php endif; ?>



                    </ul>
                    <div class="d-flex align-items-center">
                        <?php if(isset($_SESSION['USER_ID'])): ?>
                            <span class="navbar-text me-3 text-white">
                                Bienvenido, <strong><?php echo $_SESSION['USER_NAME']; ?></strong>
                            </span>
                            <a href="<?php echo BASE_URL ?>logout" class="btn btn-outline-danger btn-sm">Cerrar Sesión</a>
                        <?php else: ?>
                            <a href="<?php echo BASE_URL ?>login" class="btn btn-outline-info btn-sm">Login Admin</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main class="container mt-4">