<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Claqueta - Reseñas de Pelis</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="home">🎬 La Claqueta</a>
                
                <button class="navbar-toggler" type="button" id="btn-menu">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo BASE_URL; ?>peliculas">Ver Todas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo BASE_URL; ?>categorias">Categorías</a>
                        </li>
                    </ul>
                    <span class="navbar-text">
                        <a class="btn btn-outline-info" href="<?php echo BASE_URL; ?>login">Login Admin</a>
                    </span>
                </div>
            </div>
        </nav>
    </header>
    <main class="container mt-4">